/**
 * Generate the PUBLIC type declarations of the embeddable engine into
 * `types/engine/` — what `phantombot/engine` resolves `types` to.
 *
 *   bun run build:engine-types            # regenerate (commit the result)
 *   bun scripts/buildEngineTypes.ts --check   # fail if the committed copy is stale
 *
 * Why the output is COMMITTED: an application can depend on phantombot
 * straight from a git tag (`github:phantomyard/phantombot#v1.1.N`), and a git
 * install runs no build step. Without committed declarations its typecheck
 * would fall through to phantombot's TypeScript sources and check every
 * internal module under the application's own compiler settings.
 * `tests/engine-public-types.test.ts` runs `--check`, so a PR that changes the
 * public API without regenerating fails the suite (and therefore the release).
 *
 * `tsc -p tsconfig.engine.json` walks the whole import graph from
 * src/engine/index.ts, so it also emits declarations for internals. With
 * `stripInternal` the public declarations reference none of them; this script
 * keeps only the engine directory and fails if a public declaration imports
 * anything outside it, so an internal type can never leak into the contract.
 */

import {
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const repo = resolve(import.meta.dir, "..");
const target = join(repo, "types", "engine");
const check = process.argv.includes("--check");

const BANNER =
  "// GENERATED by scripts/buildEngineTypes.ts from src/engine/ — do not edit.\n" +
  "// Regenerate with `bun run build:engine-types` and commit the result.\n";

function fail(message: string): never {
  console.error(`build:engine-types: ${message}`);
  process.exit(1);
}

const scratch = mkdtempSync(join(tmpdir(), "phantombot-engine-types-"));
try {
  const tsc = Bun.spawnSync(
    [process.execPath, "x", "tsc", "-p", join(repo, "tsconfig.engine.json"), "--outDir", scratch],
    { cwd: repo, stdout: "inherit", stderr: "inherit" },
  );
  if (tsc.exitCode !== 0) fail(`tsc exited ${tsc.exitCode}`);

  const emitted = join(scratch, "engine");
  const generated = new Map<string, string>();
  for (const file of readdirSync(emitted).sort()) {
    if (!file.endsWith(".d.ts")) continue;
    const text = readFileSync(join(emitted, file), "utf8");
    for (const m of text.matchAll(/^(?:import|export)\b[^;]*?from\s+["']([^"']+)["']/gm)) {
      if (!m[1]!.startsWith("./")) fail(`${file}: public declaration imports ${m[1]}`);
    }
    generated.set(file, BANNER + text);
  }

  if (check) {
    let committed: string[] = [];
    try {
      committed = readdirSync(target).filter((f) => f.endsWith(".d.ts")).sort();
    } catch {
      fail("types/engine/ is missing — run `bun run build:engine-types`");
    }
    const stale = [
      ...[...generated.keys()].filter(
        (f) => !committed.includes(f) || readFileSync(join(target, f), "utf8") !== generated.get(f),
      ),
      ...committed.filter((f) => !generated.has(f)),
    ];
    if (stale.length > 0) {
      fail(
        `types/engine/ is stale (${stale.join(", ")}) — run \`bun run build:engine-types\` and commit`,
      );
    }
    console.log(`engine declarations up to date (${generated.size} files)`);
  } else {
    rmSync(target, { recursive: true, force: true });
    mkdirSync(target, { recursive: true });
    for (const [file, text] of generated) writeFileSync(join(target, file), text);
    console.log(`engine declarations: ${generated.size} files in types/engine/`);
  }
} finally {
  rmSync(scratch, { recursive: true, force: true });
}
