/**
 * Codegen: build + package the first-party VS Code extension (editors/vscode/)
 * into a `.vsix`, then embed that artifact — base64-encoded — into a TypeScript
 * constants module so phantombot's compiled single-ELF binary can stamp it onto
 * disk at runtime and run `code --install-extension <vsix>` (see
 * src/connectors/acp/installVscode.ts).
 *
 * Why an embedded base64 constants module (same shape as
 * scripts/genPiExtensionAssets.ts)?
 *   - `bun build --compile` produces a SINGLE ELF with no repo alongside it, so
 *     the shipped binary cannot fs-read `editors/vscode/*.vsix` at runtime.
 *   - `import ... with { type: "..." }` is NOT tsc-safe in this toolchain
 *     (`tsc --noEmit` rejects it). A plain generated `.ts` with the bytes as a
 *     JSON-encoded base64 string literal sidesteps that and stays
 *     `bun build --compile`-self-contained.
 *   - The `.vsix` is a binary zip; zip bytes are NOT reproducible across builds
 *     (timestamps/metadata vary), so we deliberately do NOT assert byte-exact
 *     drift. Instead the checked-in module records the extension VERSION, and
 *     tests/lib-vscodeExtensionAsset.test.ts asserts (a) the embedded version
 *     matches editors/vscode/package.json and (b) the bytes decode to a valid
 *     zip carrying the extension manifest + bundled extension.js. That catches
 *     the real failure (version bump without regen) without flaking on zip
 *     nondeterminism.
 *
 * Run: `bun run gen:vscode-vsix`. Requires network the first time (npx fetches
 * @vscode/vsce). Regenerate whenever editors/vscode/ changes.
 */

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..");
const EXT_DIR = join(REPO_ROOT, "editors", "vscode");
const OUT_FILE = join(
  REPO_ROOT,
  "src",
  "lib",
  "vscodeExtensionAsset.generated.ts",
);

const pkg = JSON.parse(
  readFileSync(join(EXT_DIR, "package.json"), "utf8"),
) as { name: string; version: string; publisher: string };

const extensionId = `${pkg.publisher}.${pkg.name}`;
const vsixFileName = `${pkg.name}-${pkg.version}.vsix`;

// ── Build + package into a throwaway temp dir, then read the bytes back. ──
const tmp = mkdtempSync(join(tmpdir(), "phantombot-vsix-"));
const vsixPath = join(tmp, vsixFileName);
try {
  // `vsce package` runs the extension's own `vscode:prepublish` (esbuild
  // bundle), so this is the full build + package pipeline in one call.
  // --no-dependencies: we bundle with esbuild, there are no runtime deps to
  // pack. --skip-license: the extension has no LICENSE file; don't fail on it.
  execFileSync(
    "npx",
    [
      "--yes",
      "@vscode/vsce@latest",
      "package",
      "--no-dependencies",
      "--skip-license",
      "--out",
      vsixPath,
    ],
    { cwd: EXT_DIR, stdio: "inherit" },
  );

  const bytes = readFileSync(vsixPath);
  const base64 = bytes.toString("base64");

  const body = [
    "// GENERATED by scripts/genVscodeVsix.ts — DO NOT EDIT. Run: bun run gen:vscode-vsix",
    "//",
    "// Embeds the built editors/vscode/ extension as a base64 .vsix so",
    "// phantombot's compiled binary can stamp it to disk and run",
    "// `code --install-extension <vsix>` (see connectors/acp/installVscode.ts).",
    "",
    `export const VSCODE_EXTENSION_ID = ${JSON.stringify(extensionId)};`,
    "",
    `export const VSCODE_EXTENSION_VERSION = ${JSON.stringify(pkg.version)};`,
    "",
    `export const VSCODE_VSIX_FILENAME = ${JSON.stringify(vsixFileName)};`,
    "",
    "/** The built .vsix, base64-encoded. Decode to bytes before writing. */",
    `export const VSCODE_VSIX_BASE64 = ${JSON.stringify(base64)};`,
    "",
  ].join("\n");

  writeFileSync(OUT_FILE, body, "utf8");
  // eslint-disable-next-line no-console
  console.log(
    `wrote ${OUT_FILE} (${extensionId}@${pkg.version}, ${bytes.length} bytes vsix, ${base64.length} base64 chars)`,
  );
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
