// GENERATED by scripts/buildEngineTypes.ts from src/engine/ — do not edit.
// Regenerate with `bun run build:engine-types` and commit the result.
/**
 * The embeddable phantombot engine.
 *
 * `createEngine({ root })` gives an application the same brain the daemon
 * runs — persona, memory, retrieval, threat screening, the harness chain with
 * fallback and watchdogs, the decision model — as a TypeScript API.
 *
 * Design, in the order it matters:
 *
 *   1. ADDITIVE. The facade calls the functions the CLI and the daemon call
 *      (`runTurn`, `makeScreener`, `applyPersona`, `runMemorySearch`, …); it
 *      re-implements none of them. The daemon never enters an engine scope,
 *      so every seam this needed (`engineScope.ts`) is a no-op for it.
 *   2. ISOLATED. Everything lives under the application's `root`: config,
 *      personas, vault, memory database, turn registry. Paths are carried by
 *      an AsyncLocalStorage scope, never by rewriting `process.env`, and the
 *      root is exclusively locked so two engines cannot share memory.
 *   3. EXPLICIT TRUST. `source` has no default. "untrusted" is screened by
 *      the threat judge before any capable harness runs; "principal" is not.
 *      Tools default to "none".
 *   4. STABLE SURFACE. Applications see `EngineEvent`, `TurnResult` and
 *      `EngineError` only — see `types.ts`.
 *
 * Runtime: Bun (the engine uses `bun:sqlite` and `Bun.spawn`, like the CLI).
 */
import type { CreatePersonaOptions, DecideOptions, DecisionResult, EngineOptions, MemoryHit, MemorySearchOptions, PersonaConfig, StructuredResult, StructuredTurnOptions, TurnOptions, TurnResult, TurnStream } from "./types.ts";
/**
 * Open an engine on `options.root`. Rejects with `invalid_root` or
 * `root_locked`. Always `close()` it (or use `await using`).
 */
export declare function createEngine(options: EngineOptions): Promise<Engine>;
export declare class Engine {
    #private;
    readonly root: string;
    readonly personas: {
        list(): Promise<string[]>;
        exists(name: string): Promise<boolean>;
        create(name: string, options?: CreatePersonaOptions): Promise<Persona>;
    };
    /** A handle on `name`. Cheap; existence is checked on use. */
    persona(name: string): Persona;
    /**
     * Cancel in-flight turns, wait for them to unwind (their harness process
     * groups are killed and their state persisted), close the memory database
     * and release the root. Idempotent.
     */
    close(): Promise<void>;
    [Symbol.asyncDispose](): Promise<void>;
    get closed(): boolean;
}
export declare class Persona {
    #private;
    readonly name: string;
    readonly secrets: {
        /** Store a credential in this persona's encrypted vault (verified by read-back). */
        set(name: string, value: string): Promise<void>;
        has(name: string): Promise<boolean>;
        delete(name: string): Promise<void>;
    };
    readonly memory: {
        /** Search this persona's memory and knowledge base (BM25F, hybrid with embeddings). */
        search(query: string, options?: MemorySearchOptions): Promise<MemoryHit[]>;
        /** Record a note in today's journal; indexed immediately. */
        capture(text: string, options?: {
            tags?: string[];
            conversation?: string;
        }): Promise<void>;
    };
    /**
     * Write this persona's brain and decision-model settings into ITS OWN
     * `config.toml` (never the root's global file, so one persona's settings
     * cannot leak into another's) and its keys into its encrypted vault.
     * Only the keys you pass are changed.
     */
    configure(settings: PersonaConfig): Promise<void>;
    /**
     * Run one turn and stream its events. Iterate it, or call `result()`, or
     * both. The stream can be consumed once.
     */
    turn(options: TurnOptions): TurnStream;
    /** Run one turn and resolve with its result. */
    ask(options: TurnOptions): Promise<TurnResult>;
    /**
     * Run a turn whose answer must be JSON that satisfies `schema`. Invalid
     * answers are retried (see `retries`) with the validation problem shown to
     * the model. Rejects with `schema_invalid` when attempts run out and with
     * `held` when the threat screen held the message.
     */
    askJson<T>(options: StructuredTurnOptions<T>): Promise<StructuredResult<T>>;
    /**
     * Ask the persona's decision model (TypeSafe Jev today, or any configured
     * decisions provider) typed questions. No harness, no
     * tools, sub-second. Rejects with `not_configured` or
     * `decision_unavailable` — never guesses an answer.
     */
    decide(options: DecideOptions): Promise<DecisionResult>;
}
