// GENERATED by scripts/buildEngineTypes.ts from src/engine/ — do not edit.
// Regenerate with `bun run build:engine-types` and commit the result.
/**
 * Internal `HarnessChunk` stream → public `EngineEvent` stream.
 *
 * The mapping is the stability boundary: harness adapters may add chunk
 * types or fields at will; applications only ever see `EngineEvent`.
 */
export {};
