// GENERATED by scripts/buildEngineTypes.ts from src/engine/ — do not edit.
// Regenerate with `bun run build:engine-types` and commit the result.
/**
 * Structured (JSON) output: the instruction that asks for it, the parser
 * that recovers it from a model reply, and the validator bridge.
 *
 * Validation is the application's schema's job (Standard Schema or a plain
 * function); this module only has to get a JSON value out of free text
 * reliably and report precisely why an answer was rejected, because that
 * report is what the retry shows the model.
 */
import type { OutputValidator } from "./types.ts";
/** Appended to the system prompt of a structured turn. */
export declare function structuredOutputInstruction(jsonSchema: Record<string, unknown> | undefined): string;
/** The follow-up message for a retry after an invalid answer. */
export declare function structuredRetryMessage(originalMessage: string, previousAnswer: string, problem: string): string;
export type ParseOutcome = {
    ok: true;
    value: unknown;
} | {
    ok: false;
    problem: string;
};
/**
 * Recover a JSON value from a reply. Accepts a bare value, a value wrapped
 * in a ```json fence, or — as a last resort — the first balanced object or
 * array in the text. Never evaluates anything.
 */
export declare function parseJsonReply(text: string): ParseOutcome;
export type ValidateOutcome<T> = {
    ok: true;
    value: T;
} | {
    ok: false;
    problem: string;
};
/** Run the application's validator; never throws. */
export declare function validateOutput<T>(validator: OutputValidator<T>, value: unknown): Promise<ValidateOutcome<T>>;
